"""empty message

Revision ID: 6a276168055b
Revises: b91854ee1982
Create Date: 2022-02-28 17:44:36.902202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a276168055b'
down_revision = 'b91854ee1982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    # ### end Alembic commands ###
