"""empty message

Revision ID: e1126fd746b9
Revises: 7b66fde8f8a6
Create Date: 2022-02-28 17:20:16.667898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1126fd746b9'
down_revision = '7b66fde8f8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('console', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tag1', sa.String(length=50), nullable=True),
    sa.Column('tag2', sa.String(length=50), nullable=True),
    sa.Column('tag3', sa.String(length=50), nullable=True),
    sa.Column('tag4', sa.String(length=50), nullable=True),
    sa.Column('tag5', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
