"""empty message

Revision ID: ef6e9eaaf37a
Revises: 2a6ee28874fa
Create Date: 2022-02-23 18:25:55.250172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6e9eaaf37a'
down_revision = '2a6ee28874fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.add_column('user', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('biography', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('img_url', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'img_url')
    op.drop_column('user', 'biography')
    op.drop_column('user', 'username')
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    # ### end Alembic commands ###
